package com.wwh.myapplication;

public class test1 {
    private String a;
    private String b;
    private String c;
    private String d;
    private String e1;
    private String f;
    private String g;
    private String a1;
    private String a2;
    private String a3;
    private String a4;
    private String a5;
    private String a6;
    private String a7;
    private String a8;
    private String a9;
    private String a10;
    private String a111;
    private String a12;
    private String a13;
    private String a14;
    private String a15;
    private String a16;
    private String a17;
    private String a18;
    private String a19;
    private String a20;
    private String a21;
    private String a22;
    private String a23;
    private String a24;
    private String a25;
    private String a26;
    private String a27;
    private String a28;
    private String a29;
    private String a30;
    private String a31;
    private String a32;
    private String a33;
    private String dev_a34;
    private String a35;
    private String a36;
    private String a37;
    private String a38;
    private String a39;
    private String a40;
    private String a41;
    private String a42;

}
